recommendations:
  # Drupal Core uses assert()
  php.quality.disable_assert_active:
    enabled: false
  # See https://www.drupal.org/project/drupal/issues/3033791
  php.quality.disable_garbage_collector:
    enabled: false
  # We need longer running requests for Drupal
  php.security.max_execution_time_too_long:
    enabled: false
  # See https://www.drupal.org/project/drupal/issues/2631220
  php.security.enable_sessions_strict_mode:
    enabled: false
  # Needs further investigation to work on PSH. See https://www.drupal.org/project/preloader/issues/3274758
  php.php_preloading:
    enabled: false
  # Really unhelpful heuristic from Blackfire here. We want to avoid someone suggesting crunching many
  # modules into one single mega-module just to greenlight this check point.
  php.drupal8.too_many_contrib_modules:
    enabled: false
  # Sigh. Yes, and if my Grandmother had wheels she would have been a bike. Most of the SQL comes from core
  # and supporting contrib modules. We can optimise some of the more complex queries but most are supporting
  # by Drupal's internal query and render caches.
  php.too_many_sqls:
    enabled: false
