recipe: drupal9
config:
  webroot: web
  php: '7.4'
  composer_version: '2.0.7'
  via: apache:2.4
  database: mariadb:10.5
  # https://docs.lando.dev/config/drupal9.html#using-drush
  # As of Drupal 9 and Drush 10 it is preferred you use a site-local install of Drush.
  # For that reason Lando will not globally install a version of Drush for Drupal 9 sites.
  drush: false
  # https://docs.lando.dev/config/drupal9.html#using-xdebug
  xdebug: false
  config:
    php: .lando/config/php.ini
    database: .lando/config/my.cnf
compose:
  - docker-compose.yml
env_file:
  - .lando/config/.env
proxy:
  # Proxy patterns here are matched on naming structure found under
  # config/sync/domain.record.group_*.yml + overridden in web/sites/default/settings.domain.php
  appserver:
    - dept.lndo.site
    - nigov.lndo.site
    - communities-ni.lndo.site
    - daera-ni.lndo.site
    - economy-ni.lndo.site
    - education-ni.lndo.site
    - executiveoffice-ni.lndo.site
    - finance-ni.lndo.site
    - health-ni.lndo.site
    - infrastructure-ni.lndo.site
    - justice-ni.lndo.site
services:
  appserver:
    scanner: false
    build_as_root:
      - /app/.lando/scripts/appserver_build.sh
  redis:
    type: redis:5.0
    # Use persist: true to persist the cache's data between restarts and rebuilds.
    persist: true
  drupal7db:
    type: mariadb
    portforward: true
    creds:
      user: drupal7
      password: drupal7
      database: drupal7
  solr:
    type: solr:7
    portforward: true
    core: default
    config:
      dir: .lando/config/solr/7.x/default
  mailhog:
    type: mailhog
    portforward: true
    hogfrom:
      - appserver
tooling:
  xdebug-on:
    service: appserver
    description: Enable xdebug
    cmd: "docker-php-ext-enable xdebug && /etc/init.d/apache2 reload"
    user: root
  xdebug-off:
    service: appserver
    description: Disable xdebug
    cmd: "rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload"
    user: root
  phpunit:
    description: "Run PHPUnit tests. You can pass options, e.g. --group=sitename"
    service: appserver
    cmd: cd /app/web/core && /app/vendor/bin/phpunit -c /app/web/core/phpunit.xml
  phpcs:
    description: Run PHPCS checks against all custom Drupal code
    service: appserver
    # Add dirs to check below, as needed.
    cmd: /app/phpcs.sh "/app" "/app/web/modules/origins /app/web/modules/custom /app/web/themes/custom"
  drck:
    description: Run drupal-check for Drupal 9 compatibility e.g. 'lando drck ./'
    service: appserver
    cmd: /app/vendor/bin/drupal-check
  drush:
    server: appserver
    cmd: /app/vendor/bin/drush -r /app/web
  yarn:
    service: appserver
    cmd: yarn
  nightwatch:
    service: appserver
    description: "Run Nightwatch.js functional tests.\n\n
                  Usage:\n
                  > Run a specific test with tag\n
                  lando nightwatch --tag your-tag\n
                  > Run a single test suite file, relative to Drupal core location\n
                  lando nightwatch ../modules/custom/modulename/tests/src/Nightwatch/Tests/yourTestSuite.js\n
                  > Run all tests except Core\n
                  lando nightwatch --skiptags core\n"
    cmd: "yarn --cwd=/app/web/core test:nightwatch"
