# This file describes an application. You can have multiple applications
# in the same project.
#
# See https://docs.platform.sh/user_guide/reference/platform-app-yaml.html

# The name of this app. Must be unique within a project.
name: 'dept'

# The runtime the application uses.
type: 'php:8.2'

variables:
  php:
    memory_limit: "128M"
#    xdebug.mode: "debug"
    display_startup_errors: "off"
    date.timezone: "Europe/Dublin"
    realpath_cache_ttl: 3600
dependencies:
  php:
    composer/composer: '^2'

runtime:
  # Enable the redis extension so Drupal can communicate with the Redis cache.
  extensions:
    - apcu
    - redis
    - blackfire
#  xdebug:
#    idekey: PHPSTORM

# The relationships of the application with services or other applications.
#
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `:`.
relationships:
  solr: 'solr_8_11:solr'
  redis: "redis:redis"
  #  For MariaDB, the endpoint does not change whether you used the mysql or mariadb service type.
  database: 'db:dept'
  drupal7db: 'drupal7db:admin'

# The size of the persistent disk of the application (in MB).
disk: 106000

# The 'mounts' describe writable, persistent filesystem mounts in the application.
mounts:
  '/web/sites/default/files':
    source: local
    source_path: 'files'
  '/tmp':
    source: local
    source_path: 'tmp'
  '/private':
    source: local
    source_path: 'private'
  '/imports':
    source: local
    source_path: 'imports'
  '/log':
    source: local
    source_path: 'log'
  '/.drush':
    source: local
    source_path: 'drush'
  '/drush-backups':
    source: local
    source_path: 'drush-backups'
  '/.console':
    source: local
    source_path: 'console'

# Configuration of the build of this application.
build:
  flavor: composer

# The hooks executed at various points in the lifecycle of the application.
hooks:
  build: |
    set -e
    echo ">>> Replace vanilla CKEditor config with a custom one to fix the click/drag bug with embedded entities"
    git clone https://github.com/dof-dss/ckeditor4-fix-widget-dnd.git
    rm -rf web/core/assets/vendor/ckeditor
    mv ckeditor4-fix-widget-dnd/build/ckeditor web/core/assets/vendor/ckeditor
    rm -rf ckeditor4-fix-widget-dnd
    echo ">>> Install Platform CLI tool"
    curl -fsSL https://raw.githubusercontent.com/platformsh/cli/main/installer.sh | bash
    echo "Update robots.txt with customisations"
    cp -f robots_custom.txt web/robots.txt
  # The deploy hook runs after your application has been deployed and started.
  deploy: |
    set -e
    php ./drush/platformsh_generate_drush_yml.php
    cd web
    # Rebuild caches, run db-updates and import config.
    ../vendor/bin/drush -y cache-rebuild
    ../vendor/bin/drush -y updatedb
    # General config import
    ../vendor/bin/drush -y config-import
    # Final cache rebuild.
    ../vendor/bin/drush -y cache-rebuild
  post_deploy: |
    set -e
    echo "***** Creating QA accounts ******"

    cd /app/web

    echo "$QA_USERNAMES" | tr ',' '\n' | while read username; do
      echo $item
      ../vendor/bin/drush ucrt $username --password=$QA_PASSWORD
      ../vendor/bin/drush urol administrator $username
    done

# The configuration of app when it is exposed to the web.
web:
  # Specific parameters for different URL prefixes.
  locations:
    '/':
      # The folder from which to serve static assets, for this location.
      #
      # This is a filesystem path, relative to the application root.
      root: 'web'

      # How long to allow static assets from this location to be cached.
      #
      # Can be a time in seconds, or -1 for no caching. Times can be
      # suffixed with "s" (seconds), "m" (minutes), "h" (hours), "d"
      # (days), "w" (weeks), "M" (months, as 30 days) or "y" (years, as
      # 365 days).
      expires: 5m

      # Whether to forward disallowed and missing resources from this
      # location to the application.
      #
      # Can be true, false or a URI path string.
      passthru: '/index.php'

      # Deny access to static files in this location.
      allow: false

      # Rules for specific URI patterns.
      rules:
        # Allow access to common static files.
        '\.(jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf)$':
          allow: true
          expires: 2w
        '^/robots\.txt$':
          allow: true
        '^/sitemap\.xml$':
          allow: true
        '^\/themes\/custom\/.+\/favicons\/.+\.webmanifest$':
          allow: true
          expires: 2w

        # Deny direct access to configuration files.
        '^/sites/sites\.php$':
          scripts: false
        '^/sites/[^/]+/settings.*?\.php$':
          scripts: false

    '/sites/default/files':
      # Allow access to all files in the public files directory.
      allow: true
      expires: 1d
      passthru: '/index.php'
      root: 'web/sites/default/files'

      # Do not execute PHP scripts.
      scripts: false

      rules:
        # Provide a longer TTL (2 weeks) for aggregated CSS and JS files.
        '^/sites/default/files/(css|js)':
          expires: 2w

# Set up migration content refresh every night.
crons:
  daily_edge_solr_reindex:
    spec: '0 6 * * 0-5'
    cmd: './reindex-edge-solr.sh'
  d7db:
    spec: '0 1 * * *'
    cmd: 'migrate-scripts/sync-db.sh $D7_PROJECT_ID $D7_PROJECT_ENV'
  drupal:
    spec: '*/15 * * * *'
    cmd: 'vendor/bin/drush cron'
  migrate:
    spec: '30 2 * * *'
    cmd: 'migrate-scripts/migrate.sh 2>&1 | tee /app/imports/last-migrate-output.txt'
  sync_files:
    spec: '30 0 * * *'
    cmd: 'migrate-scripts/sync-private-files.sh $D7_PROJECT_ID $D7_PROJECT_ENV'
  logging:
    spec: '*/5 * * * *'
    commands:
      start: '/bin/bash /app/cronjob.sh'
    shutdown_timeout: 290
