<?php

/**
 * @file
 * mDash module hooks.
 */

/**
 * Implements hook_theme().
 */
function dept_mdash_theme($existing, $type, $theme, $path) {
  return [
    'mdash_dashboard' => [
      'variables' => [
        'content_summary' => NULL,
        'error_summary' => NULL,
        'relationship_summary' => NULL,
        'last_migration' => NULL,
        'group_relationships' => NULL,
        'last_group_relationships_process' => NULL,
        'null_destination_nodes' => NULL,
        'log_output' => NULL,
      ],
    ],
  ];
}
