<?php


use Drupal\dept_ui\Entity\Node;
use Drupal\dept_ui\Form\NodeForm;

/**
 * @file
 * Primary module hooks for User Interface module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_entity_type_alter().
 */
function dept_ui_entity_type_alter(&$entity_types) {
  if (isset($entity_types['node'])) {
    $entity_types['node']->setClass(Node::class);

    foreach (['default', 'edit'] as $operation) {
      $entity_types['node']->setFormClass($operation, NodeForm::class);
    }
  }
}

