<?php


use Drupal\dept_ui\Entity\Node;
use Drupal\dept_ui\Form\NodeForm;

/**
 * @file
 * Primary module hooks for User Interface module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

//function dept_ui_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
//  $group_membership = \Drupal::getContainer()->get('group.membership_loader');
//
//  $user_memberships = $group_membership->loadByUser();
//
//  foreach ($user_memberships as $membership) {
//    $group = $membership->getGroup();
//    ksm($group);
//    $group_options[$group->id()] = $group->label();
//  }
//
//  $form['group_publish'] = [
//    "#title" => t('Groups'),
//    "#type" => "details",
//    '#open' => TRUE,
//    "#group" => "advanced",
//    '#weight' => -50,
//  ];
//
//  $form['group_publish']['groups'] = [
//    "#type" => "checkboxes",
//    "#options" => $group_options,
//  ];
//}

/**
 * Implements hook_entity_type_alter().
 */
function dept_ui_entity_type_alter(&$entity_types) {
  if (isset($entity_types['node'])) {
    $entity_types['node']->setClass(Node::class);
    
    foreach (['default', 'edit'] as $operation) {
      $entity_types['node']->setFormClass($operation, NodeForm::class);
    }
  }
}

