<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * @file
 * Primary module hooks for User Interface module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

function dept_ui_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $groups = \Drupal::entityTypeManager()->getStorage('group')->loadMultiple();
  $group_membership = \Drupal::getContainer()->get('group.membership_loader');

  $user_memberships = $group_membership->loadByUser();

  foreach ($user_memberships as $membership) {
    $group = $membership->getGroup();
    $group_options[$group->id()] = $group->label();
  }

  $form['group_publish'] = [
    "#title" => t('Groups'),
    "#type" => "details",
    '#open' => TRUE,
    "#group" => "advanced",
    '#weight' => -50,
  ];

  $form['group_publish']['groups'] = [
    "#type" => "checkboxes",
    "#options" => $group_options,
  ];
}
