version: 2.1

parameters:
  repo:
    type: string
  branch:
    type: string

jobs:
  generate-config:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Generate dynamic config
          command: |
            # Fetch the shared config from your central repo
            SHARED_CONFIG_URL="https://raw.githubusercontent.com/johangant/ci-config/DEPT-1217--shared-config/shared-config.yml"
            curl -s -o shared-config.yml $SHARED_CONFIG_URL

            # Generate the final config by combining with project specifics
            cat << EOF > generated-config.yml
            version: 2.1

            # Import the shared config
            <<: *shared-config.yml

            # Project-specific overrides
            parameters:
              php_version:
                type: string
                default: "8.1" # Override default for this project

              test_command:
                type: string
                default: "vendor/bin/phpunit --testsuite=unit"

            workflows:
              test-and-lint:
                jobs:
                  - php-tests:
                      name: "PHP << matrix.php_version >> Tests"
                      matrix:
                        parameters:
                          php_version: ["7.4", "8.0", "8.1", "8.2"]
                  - lint-code

            jobs:
              php-tests:
                executor: php-executor
                parameters:
                  php_version:
                    type: string
                steps:
                  - setup-php
                  - run-tests:
                      test_command: << parameters.test_command >>
            EOF

            # Output the config for CircleCI to use
            cat generated-config.yml > /tmp/workspace/generated-config.yml
    outputs:
      config:
        path: /tmp/workspace/generated-config.yml

workflows:
  generate-config:
    jobs:
      - generate-config
      - validate:
          requires:
            - generate-config
          config: << pipeline.parameters.config >>
