version: 2.1

workflows:
  build-test:
    jobs:
      - build:
          php_version: << pipeline.parameters.php_version >>
          ssh_fingerprint: << pipeline.parameters.ssh_fingerprint >>
      - coding_standards:
          requires:
            - build
          php_version: << pipeline.parameters.php_version >>
          coding_standards_dirs: << pipeline.parameters.coding_standards_dirs >>
          ignore_dirs: << pipeline.parameters.ignore_dirs >>
      - deprecated_code:
          requires:
            - build
          php_version: << pipeline.parameters.php_version >>
          deprecated_code_dirs: << pipeline.parameters.deprecated_code_dirs >>
      - disallowed_functions:
          requires:
            - build
          php_version: << pipeline.parameters.php_version >>
          custom_code_dirs: << pipeline.parameters.custom_code_dirs >>
