version: 2.1

workflows:
  build-test:
    jobs:
      - build:
          php_version: << pipeline.parameters.php_version >>
          ssh_fingerprint: << pipeline.parameters.ssh_fingerprint >>
      - coding_standards:
          requires:
            - build
          php_version: << pipeline.parameters.php_version >>
          coding_standards_dirs: << pipeline.parameters.coding_standards_dirs >>
          ignore_dirs: << pipeline.parameters.ignore_dirs >>
      - deprecated_code:
          requires:
            - build
          php_version: << pipeline.parameters.php_version >>
          deprecated_code_dirs: << pipeline.parameters.deprecated_code_dirs >>
      - disallowed_functions:
          requires:
            - build
          php_version: << pipeline.parameters.php_version >>
          custom_code_dirs: << pipeline.parameters.custom_code_dirs >>
  build-edge:
    triggers:
      - schedule:
          # At 02:00 every Mon-Fri
          cron: "0 2 * * 1-5"
          filters:
            branches:
              only:
                - development
    jobs:
      - build_edge:
          php_version: << pipeline.parameters.php_version >>
          edge_branch: << pipeline.parameters.edge_branch >>
          edge_build_dofdss_packages: << pipeline.parameters.edge_build_dofdss_packages >>
  # A separate scheduled workflow to sync the data after the edge build completes.
  build-edge-finalise:
    triggers:
      - schedule:
          # At 02:30 on every day-of-week from Monday through Friday
          cron: "30 2 * * 1-5"
          filters:
            branches:
              only:
                - DEPT-edge
    jobs:
      - sync_data:
          php_version: << pipeline.parameters.php_version >>
          edge_branch: << pipeline.parameters.edge_branch >>
