<?php

/**
 * @file
 * Primary module hooks for Departmental sites: Sitemaps module.
 */

use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\dept_core\Entity\Department;
use Drupal\simple_sitemap\Entity\SimpleSitemapInterface;

/**
 * Implements hook_simple_sitemap_links_alter().
 */
function dept_sitemap_simple_sitemap_links_alter(array &$links, SimpleSitemapInterface $sitemap) {

  // If an entity in the sitemap links array does not have 'nigov' as it's
  // domain source, remove it from the generated links.
  if ($sitemap->id() != 'nigov') {
    return;
  }

  foreach ($links as $key => $link) {
    $entity_info = $link['meta']["entity_info"] ?? NULL;
    if (empty($entity_info)) {
      continue;
    }

    $entity = \Drupal::entityTypeManager()->getStorage($entity_info['entity_type'])->load($entity_info['id']);

    if ($entity instanceof ContentEntityInterface  && $entity->hasField('field_domain_source')) {
      if ($entity->get('field_domain_source')->getString() != 'nigov') {
        unset($links[$key]);
      }
    }
  }
}
