<?php

/**
 * @file
 * Core functionality for Departmental sites.
 */

use Drupal\Core\Template\Attribute;
use Drupal\Core\Url;
use Drupal\group\Entity\Group;
use Drupal\node\NodeInterface;

/**
 * Implements hook_preprocess_page().
 */
function dept_core_preprocess_page(&$variables) {
  $dept_manager = \Drupal::service('department.manager');
  $variables['department'] = $dept_manager->getCurrentDepartment();
}

/**
 * Implements hook_preprocess_menu().
 */
function dept_core_preprocess_menu(&$variables) {
  if ($variables['menu_name'] === 'footer' && !empty($variables['items'])) {
    // Add a menu link to the end of the menu with a link to the
    // accessibility statement defined in the group field value.
    $dept = \Drupal::service('department.manager')->getCurrentDepartment();
    if (empty($dept)) {
      return;
    }

    $group = Group::load($dept->groupId());

    if (empty($group)) {
      return;
    }

    // Footer menu doesn't vary much at all so use a very broad context.
    // See https://www.drupal.org/docs/drupal-apis/cache-api/cache-contexts#core-contexts
    $variables['#cache']['contexts'] = ['theme'];
    $variables['#cache']['tags'][] = 'group:' . $group->id();

    $accessibility_statement_node = $group->field_accessibility_statement->referencedEntities();
    if (!empty($accessibility_statement_node)) {
      $accessibility_statement_node = $accessibility_statement_node[0];

      if ($accessibility_statement_node instanceof NodeInterface) {
        // See MenuLinkTree->buildItems() which this imitates.
        $menu_link = [
          'title' => $accessibility_statement_node->getTitle(),
          'url' => Url::fromRoute('entity.node.canonical', ['node' => $accessibility_statement_node->id()]),
          'is_collapsed' => FALSE,
          'is_expanded' => FALSE,
          'in_active_trail' => FALSE,
          'attributes' => new Attribute(),
        ];

        $variables['items'][] = $menu_link;
        $variables['#cache']['tags'][] = 'node:' . $accessibility_statement_node->id();
      }
    }
  }
}
