<?php

/**
 * @file
 * Core functionality for Departmental sites.
 */

use Drupal\Core\Cache\Cache;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Template\Attribute;
use Drupal\Core\Url;
use Drupal\Core\Link;
use Drupal\node\NodeInterface;

/**
 * Implements hook_preprocess_page().
 */
function dept_core_preprocess_page(&$variables) {
  dept_core_append_dept_info_for_templates($variables);
}

/**
 * Implements hook_preprocess_node().
 */
function dept_core_preprocess_node(&$variables) {
  dept_core_append_dept_info_for_templates($variables);
}

/**
 * Implements hook_preprocess_field().
 */
function dept_core_preprocess_field(&$variables) {
  dept_core_append_dept_info_for_templates($variables);
}

/**
 * Implements hook_preprocess_menu().
 */
function dept_core_preprocess_menu(&$variables) {
  if ($variables['menu_name'] === 'footer' && !empty($variables['items'])) {
    // Add a menu link to the end of the menu with a link to the
    // accessibility statement defined in the group field value.
    $dept = \Drupal::service('department.manager')->getCurrentDepartment();

    // @phpstan-ignore-next-line
    if (empty($dept)) {
      return;
    }

    // Footer menu doesn't vary much at all so use a very broad context.
    // See https://www.drupal.org/docs/drupal-apis/cache-api/cache-contexts#core-contexts

    if (($accessibility_statement = $dept->accessibilityStatement()) !== NULL && $accessibility_statement instanceof NodeInterface) {
      // See MenuLinkTree->buildItems() which this imitates.
      $menu_link = [
        'title' => 'Accessibility statement',
        'url' => Url::fromRoute('entity.node.canonical', ['node' => $accessibility_statement->id()]),
        'is_collapsed' => FALSE,
        'is_expanded' => FALSE,
        'in_active_trail' => FALSE,
        'attributes' => new Attribute(),
      ];

      $cache_tags[] = 'node:' . $accessibility_statement->id();

      if (!empty($variables['#cache']['tags'])) {
        $variables['#cache']['tags'] = Cache::mergeTags($cache_tags, $variables['#cache']['keys']);
      }

      $variables['items'][] = $menu_link;
      $variables['#cache']['tags'] = $cache_tags;
    }

  }
}

/**
 * Function that adds department object metadata to
 * preprocess variables for use in templates.
 */
function dept_core_append_dept_info_for_templates(array &$variables) {
  $dept_manager = \Drupal::service('department.manager');
  /** @var \Drupal\dept_core\Entity\Department $dept */
  $dept = $dept_manager->getCurrentDepartment();

  // Object properties/method values set as preprocess variables
  // to remain compliant with Twig sandbox configuration which
  // prohibits direct access to many object properties (security reasons)
  // except for those on a pre-defined method allow-list.
  // See https://chromatichq.com/insights/custom-entity-methods-twig-templates/
  // and https://www.drupal.org/forum/support/theme-development/2018-09-05/twig-sandbox-security-error-when-calling-object-method
  $variables['department']['id'] = $dept->id();
  $variables['department']['name'] = $dept->name();
}

/**
 * Implements hook_entity_update().
 */
function dept_core_entity_update(EntityInterface $entity) {

  // Update the corresponding Department label when a Domain label is updated.
  if ($entity->getEntityType()->id() == 'domain' && !$entity->isNew()) {
    $department = \Drupal::entityTypeManager()->getStorage('department')->load($entity->id());

    if (!empty($department) && $department->label() !== $entity->label()) {
      // @phpstan-ignore-next-line
      $department->set('label', $entity->label());
      $department->save();
    }
  }
}

/**
 * Implements hook_token_info().
 */
function dept_core_token_info() {

  $types['departmental'] = [
    'name' => t("Departmental"),
    'description' => t("Departmental site tokens"),
  ];

  $tokens['all-departments-links'] = [
    'name' => t("Departments links"),
    'description' => t("Displays a list of links to each department site"),
  ];

  return [
    'types' => $types,
    'tokens' => [
      'departmental' => $tokens,
    ],
  ];
}

/**
 * Implements hook_tokens().
 */
function dept_core_tokens($type, $tokens, array $data, array $options, $bubbleable_metadata) {

  $replacements = [];

  if ($type === 'departmental') {
    foreach ($tokens as $name => $original) {
      switch ($name) {
        // Display a list of links to each Department.
        case 'all-departments-links':

          $departments = \Drupal::entityTypeManager()->getStorage('department')->loadByProperties(['status' => TRUE]);
          $links = [];

          foreach ($departments as $department) {
            // @phpstan-ignore-next-line
            $links[] = Link::fromTextAndUrl($department->label(), Url::fromUri('https://' . $department->hostname()))->toRenderable();
          }

          $link_list = [
            '#theme' => 'item_list',
            '#list_type' => 'ul',
            '#items' => $links,
          ];

          $replacements[$original] = \Drupal::service('renderer')->render($link_list);
          break;
      }
    }
  }

  return $replacements;
}
