# Schema for the configuration files of the Origins cloud tasks module.
origins_cloud_tasks.settings:
  type: config_object
  label: 'Origins cloud tasks settings'
  mapping:
    callback_offset:
      type: string
      label: 'Callback offset'
