<?php

/**
 * @file hooks for dept_migrate_audit module.
 */

use Drupal\Core\Database\Database;

/**
 * Implements hook_cron().
 */
function dept_migrate_audit_cron() {
  dept_migrate_audit_truncate_table();
  $results = dept_migrate_audit_fetch_d7_uuids();

  if (!empty($results)) {
    dept_migrate_audit_populate_table_with_new_data($results);
  }
}

/**
 * Callback to truncate the audit table.
 */
function dept_migrate_audit_truncate_table() {
  \Drupal::database()->truncate('dept_migrate_audit')->execute();
}

/**
 * Callback to fetch suitable D7 uuids and type data from the migrate DB.
 * NB: includes a type map which will omit some D7 specific types
 * such as webform.
 */
function dept_migrate_audit_fetch_d7_uuids() {
  $d7conn = Database::getConnection('default', 'migrate');
  $results = $d7conn->query("SELECT `uuid`, `type` FROM {node} WHERE `type` IN (:types[])", [
    ':types[]' => [
      'application',
      'article',
      'collection',
      'consultation',
      'contact',
      'gallery',
      'heritage_site',
      'link',
      'news',
      'page',
      'protected_area',
      'publication',
      'secure_publication',
      'subtopic',
      'topic',
      'ual',
    ]
  ])->fetchAll();

  return $results;
}

/**
 * Callback to populate the audit table with results from D7.
 */
function dept_migrate_audit_populate_table_with_new_data(array $results) {
  if (empty($results)) {
    return;
  }

  $now = \Drupal::time()->getCurrentTime();

  // Use multi-insert format for efficiency.
  // See https://www.drupal.org/docs/drupal-apis/database-api/insert-queries#multi-insert-form.
  $query = \Drupal::database()
    ->insert('dept_migrate_audit')
    ->fields(['uuid', 'type', 'last_import']);
  foreach ($results as $index => $row) {
    $query->values([$row->uuid, $row->type, $now]);
  }

  $query->execute();
}
