<?php

/**
 * @file
 * Primary module hooks for Origins File System module.
 */


/**
 * Implements hook_views_data().
 */
function dept_fs_views_data() {
  $data = [];

  $data['media_duplicates'] = [];

  $data['media_duplicates']['table']['group'] = t('Media Duplicates');
  $data['media_duplicates']['table']['base'] = [
    'field' => 'id',
    'title' => t('Media Duplicates'),
    'help' => t('Media file duplicated based on filehashes.'),
    'weight' => -10,
  ];

  // Fields.
  $data['media_duplicates']['id'] = [
    'title' => t('ID'),
    'help' => t('Duplicate ID'),
    'field' => [
      'id' => 'standard',
    ],
    'filter' => [
      'id' => 'numeric',
    ],
    'argument' => [
      'id' => 'numeric',
    ],
    'sort' => [
      'id' => 'standard',
    ],
  ];

  $data['media_duplicates']['group_id'] = [
    'title' => t('Group ID'),
    'help' => t('The duplicate group the file belongs to.'),
    'field' => [
      'id' => 'numeric',
    ],
    'filter' => [
      'id' => 'numeric',
    ],
    'argument' => [
      'id' => 'numeric',
    ],
    'sort' => [
      'id' => 'standard',
    ],
  ];

  $data['media_duplicates']['mid'] = [
    'title' => t('Media ID'),
    'help' => t('the Media entity ID'),
    'field' => [
      'id' => 'standard',
    ],
    'filter' => [
      'id' => 'numeric',
    ],
    'argument' => [
      'id' => 'numeric',
    ],
    'relationship' => [
      'title' => t('Media entity'),
      'help' => t('The Media entity.'),
      'base' => 'media_field_data',
      'base field' => 'mid',
      'id' => 'standard',
    ],
  ];

  $data['media_duplicates']['checksum'] = [
    'title' => t('Checksum'),
    'help' => t('The Media entity file checksum'),
    'field' => [
      'id' => 'standard',
    ],
    'sort' => [
      'id' => 'standard',
    ],
    'filter' => [
      'id' => 'string',
    ],
    'argument' => [
      'id' => 'string',
    ],
  ];

  $data['media_duplicates']['created'] = [
    'title' => t('Created'),
    'help' => t('The date of the duplicate analysis.'),
    'field' => [
      'id' => 'date',
    ],
    'sort' => [
      'id' => 'date',
    ],
    'filter' => [
      'id' => 'date',
    ],
  ];


  return $data;
}
