<?php

/**
 * @file
 * Primary module hooks for Origins File System module.
 */

use Drupal\Core\Database\Query\AlterableInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_entity_base_field_info().
 */
function dept_fs_entity_base_field_info(EntityTypeInterface $entity_type) {
  if ($entity_type->id() === 'media') {
    $fields['duplicates_checksum'] = BaseFieldDefinition::create('string')
      ->setLabel(t('Duplicates checksum'))
      ->setDescription(t('SHA256 hash of the media file, used for duplicate detection.'))
      ->setRevisionable(FALSE)
      ->setTranslatable(FALSE)
      ->setReadOnly(TRUE)
      ->setSetting('max_length', 64)
      ->setDisplayOptions('view', ['region' => 'hidden'])
      ->setDisplayConfigurable('view', FALSE)
      ->setDisplayConfigurable('form', FALSE);
    return $fields;
  }
}


/**
 * Implements hook_views_pre_render().
 */
function dept_fs_views_pre_render(ViewExecutable $view) {
  if ($view->id() === 'media_duplicates') {

    $view->element['#attached']['library'][] = 'dept_fs/media-duplicates';
  }
}

/**
 * Implements hook_media_duplicates_checksum_info_alter().
 */
function dept_fs_media_duplicates_checksum_info_alter(array &$providers) {
  // Remove the default file processor as we replace it with our GoFileProcessor.
  unset($providers['file']);
}

/**
 * Implements hook_views_query_alter().
 */
function dept_fs_views_query_alter(ViewExecutable $view, $query) {
  if ($view->id() === 'media_duplicates') {
    $query->addTag('media_duplicates_group_filter');
  }
}

/**
 * Implements hook_query_TAG_alter().
 */
function dept_fs_query_media_duplicates_group_filter_alter(AlterableInterface $query) {
//  $database = \Drupal::database();
//
//  // We only want to return rows that have at least more than 1 matching
//  // checksum and ignore rows that don't have a checksum value.
//  $checksum_query = $database->select('media_field_data', 'mfd')
//    ->fields('mfd', ['duplicates_checksum'])
//    ->isNotNull('mfd.duplicates_checksum')
//    ->groupBy('mfd.duplicates_checksum')
//    ->having('COUNT(mfd.mid) > 1');
//
//  $query->condition('media_field_data.duplicates_checksum', $checksum_query, 'IN');
//  $query->isNotNull('media_field_data.duplicates_checksum');

}
