<?php

/**
 * @file
 * Primary module hooks for Dept postprocess module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_form_node_form_alter().
 */
function dept_postprocess_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Create a new 'hide topic' checkbox on the main node form that mirrors the functionality
  // of the Flag checkbox under the 'advanced' section.
  if (in_array($form_id, ['node_topic_form', 'node_topic_edit_form'])) {
    if (array_key_exists('flag', $form) && array_key_exists('hide_listing', $form["flag"])) {
      $form['hide_listing'] = [
        '#type' => 'checkbox',
        '#title' => $form["flag"]['hide_listing']['#title'],
        '#description' => $form["flag"]['hide_listing']['#description'],
        '#default_value' => $form["flag"]['hide_listing']['#default_value'],
        '#weight' => 1,
      ];

      $form["flag"]['hide_listing']['#states'] = [
        'checked' => [
          ':input[name="hide_listing"]' => ['checked' => TRUE],
        ],
      ];
    }
  }

  $form_object = $form_state->getFormObject();
  // @phpstan-ignore-next-line
  $bundle = $form_object->getEntity()->bundle();
  $dept_manager = \Drupal::service('department.manager');
  $current_dept = $dept_manager->getCurrentDepartment();

  // Checks the Domain Path by default when logged in with Domain Path
  // permissions on a node form.
  if ($bundle === 'topic' || $bundle === 'subtopic') {
    $form['domain_path'][$current_dept->id()]['pathauto']['#default_value'] = 1;
  }
}

/**
 * Implements hook_moderation_sidebar_alter().
 */
function dept_postprocess_moderation_sidebar_alter(&$build, &$context) {
  if ($context instanceof NodeInterface &&
    in_array($context->bundle(), ['topic', 'subtopic'])) {

    $has_active_children = \Drupal::service('topic.manager')->topicHasActiveChildren($context);

    // If the topic has active child content, replace (disable) the archive button.
    if ($has_active_children &&
      ((isset($build["actions"]["primary"]["quick_draft_form"]) &&
        array_key_exists('archive', $build["actions"]["primary"]["quick_draft_form"])) ||
      (isset($build["actions"]["primary"]) &&
        array_key_exists('archive', $build["actions"]["primary"])))) {

      $build["actions"]["primary"]["quick_draft_form"]['archive'] = [
        '#type' => 'html_tag',
        '#tag' => 'div',
        '#value' => t('Archive'),
        '#weight' => 1,
        '#attributes' => [
          'class' => ['moderation-sidebar-link', 'button', ''],
          'disabled' => 'disabled',
          'style' => "cursor: not-allowed",
          'title' => t('This content has active child pages. It cannot be archived until child pages have been reallocated to a different topic, archived or deleted.'),
        ],
      ];
    }

    // If the topic has active child content, disable the delete button.
    if (isset($build["actions"]["primary"]["delete"]) && $has_active_children) {
      $build["actions"]["primary"]["delete"] = [
        '#type' => 'html_tag',
        '#tag' => 'div',
        '#value' => t('Delete'),
        '#weight' => 1,
        '#attributes' => [
          'class' => ['moderation-sidebar-link', 'button', 'button--danger'],
          'disabled' => 'disabled',
          'style' => "cursor: not-allowed",
          'title' => t('This content has active child pages. It cannot be deleted until child pages have been reallocated to a different topic, archived or deleted.'),
        ],
      ];
    }

    if (!\Drupal::currentUser()->hasPermission('edit any subtopic content')) {
      // Remove sidebar actions for topics/subtopic if the user does not have
      // the edit subtopic permission.

      // Primary actions.
      foreach (['quick_draft_form', 'draft_of_published', 'archive'] as $action) {
        if (isset($build['actions']["primary"][$action])) {
          unset($build['actions']["primary"][$action]);
        }
      }

      // Secondary actions.
      foreach (['version_history', 'entity.node.book_outline_form'] as $action) {
        if (isset($build['actions']["secondary"][$action])) {
          unset($build['actions']["secondary"][$action]);
        }
      }
    }

  }
}
