adding:
  backend_config:
    connector: solr_cloud_basic_auth
    connector_config:
      host: solr
      port: 8983
      skip_schema_check: true
      solr_install_dir: /opt/solr
      checkpoints_collection: ''
      stats_cache: org.apache.solr.search.stats.LRUStatsCache
      distrib: true
      context: solr
      username: solr
      password: SolrRocks
removing:
  backend_config:
    connector: standard
    connector_config:
      host: solr.internal
      port: 8080
      skip_schema_check: false
      solr_install_dir: ''
