toolbar_items:
  - devel.configs_list
  - devel.container_info.service
  - devel.elements_page
  - devel.entity_info_page
  - devel.field_info_page
  - devel.reinstall
  - devel.route_info
  - devel.theme_registry
