_core:
  default_config_hash: PJP3-sJN2SQZTgCupMBEHry3ui7zsl93xtTovoTanFU
langcode: en
remember_domain: true
path_pages: "/admin/appearance\r\n/admin/config/system/site-information\r\n/admin/group/settings\r\n/admin/config/search/metatag\r\n/admin/config/search/metatag/*"
