workflows:
  build-test:
    jobs:
      - build:
          php_version: << pipeline.parameters.php_version >>
          ssh_fingerprint: << pipeline.parameters.ssh_fingerprint >>
      - coding_standards:
          requires:
            - build
          php_version: << pipeline.parameters.php_version >>
          coding_standards_dirs: << pipeline.parameters.coding_standards_dirs >>
      - deprecated_code:
          requires:
            - build
          php_version: << pipeline.parameters.php_version >>
          deprecated_code_dirs: << pipeline.parameters.deprecated_code_dirs >>
  build-edge:
    triggers:
      - schedule:
          cron: "0 2 * * *"
          filters:
            branches:
              only:
                - development
    jobs:
      - build_edge:
          php_version: << pipeline.parameters.php_version >>
          edge_branch: << pipeline.parameters.edge_branch >>
          edge_build_dofdss_packages: << pipeline.parameters.edge_build_dofdss_packages >>
