vuuid: 75e81ae8-827b-46f7-bfb9-4e1bb6dc5118
langcode: en
status: true
dependencies: {  }
_core:
  default_config_hash: sL588ui1E_8-2c_UupwyYxcqX2OVyMFp3HTLbbFqvPc
id: global
label: Global
tags:
  canonical_url: '[current-page:url:absolute]'
  google_site_verification: TpnKRSwKCPcd_hpX9EavYkai-uMQ9618-jNsGBh4ABY
  og_site_name: '[site:name]'
  shortlink: '[current-page:url:unaliased]'
  title: '[current-page:title] | [site:name]'
