<?php

/**
 * @file
 * Departmental Node module for Departmental sites.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Link;
use Drupal\dept_node\Entity\Node;
use Drupal\dept_node\Form\NodeForm;
use Drupal\dept_node\FormatHelper;
use Drupal\node\NodeInterface;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_form_ENTITY_form_alter().
 */
function dept_node_form_node_form_alter(&$form, $form_state) {

  // Add handler to process nodes that should have 'nigov' entries.
  if (in_array($form_state->getFormObject()->getEntity()->bundle(), [
    'consultation',
    'publication',
    'news'
  ])) {
    foreach (array_keys($form['actions']) as $action) {
      if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
        array_unshift($form['actions'][$action]['#submit'], 'dept_node_assign_domain_defaults');
      }
    }
  }

  $docs_field_ids = [
    'field_attachment',
    'field_publication_files',
    'field_publication_secure_files',
  ];

  if (!empty(array_intersect(array_keys($form), $docs_field_ids))) {
    $form['#attached']['library'][] = 'nicsdru_origins_theme/media_library_styles';
  }

  // Set Domain Source as required as we need this for features such as LinkIt
  // to function properly.
  $form['field_domain_source']['widget']['#required'] = TRUE;

  // Set the Domain source entry if not already provided.
  if (empty($form['field_domain_source']['widget']['#default_value'])) {
    $domain_access_ids = $form['field_domain_access']['widget']['#default_value'];

    if (count($domain_access_ids) > 1) {
      // Exclude NIGov as a domain entry as that site should not be publishing
      // content.
      $domain_access_ids = array_values(array_filter(array_map(function ($val) {
        if ($val !== 'nigov') {
          return $val;
        }
      }, $domain_access_ids)));
    }

    $form['field_domain_source']['widget']['#default_value'][] = $domain_access_ids[0];
  }
}

/**
 * Implements hook_views_pre_render().
 */
function dept_node_views_pre_render(ViewExecutable $view) {
  // Append the active site name to a few fields/titles for publications RSS.
  if ($view->id() === 'press_releases') {
    $site_name = \Drupal::config('system.site')->get('name');
    $title = t('Latest press releases from ') . $site_name;
    $view->setTitle($title);

    if (\Drupal::routeMatch()->getRouteName() === 'entity.view.preview_form') {
      \Drupal::messenger()
        ->addWarning('NB: Title altered in dept_node_views_pre_render()');
    }
  }
}

/**
 * Implements hook_theme().
 */
function dept_node_theme($existing, $type, $theme, $path) {
  return [
    'topics_subtopics_list' => [
      'variables' => [
        'title' => NULL,
        'items' => NULL,
        'links' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_topics_subtopics_list().
 */
function dept_node_preprocess_topics_subtopics_list(array &$variables) {
  if ($variables['links']) {
    $link_items = [];

    foreach ($variables['items'] as $id => $title) {
      $link_items[] = Link::createFromRoute($title, 'entity.node.canonical', ['node' => $id])->toString();
    }

    // Replace the text list with link equivalents.
    $variables['items'] = $link_items;
  }
}

/**
 * Implements hook_preprocess_node().
 */
function dept_node_preprocess_node(array &$variables) {
  /** @var \Drupal\node\NodeInterface $node */
  $node = &$variables['node'];
  $view_mode = $variables['view_mode'];
  $routename = \Drupal::routeMatch()->getRouteName();

  if (!$node instanceof NodeInterface) {
    return;
  }

  // Add the topic banner to the output, if relevant.
  dept_node_topic_banner($variables);

  if (str_starts_with($view_mode, 'search_') && $node->bundle() === 'news') {
    // Add the department metadata on the press-releases listing.
    if ($routename != 'view.news_search.press_release_search') {
      return;
    }

    // Rewrite any existing relative URLs to content to their absolute
    // departmental URL paths, using active config split profile values.
    if (!preg_match('|^http|', $variables['url'])) {
      $variables['url'] = \Drupal::service('rel2abs_url')
        ->handleUrl($variables['url'], $node);
    }
  }

  if (str_starts_with($view_mode, 'search_') && $node->bundle() === 'consultation') {
    $consultation_dates = $node->get('field_consultation_dates')->getValue();
    // Set the consultation status to open/closed based on its date values.
    $now = \Drupal::service('datetime.time')->getCurrentTime();
    $consultation_end = strtotime($consultation_dates[0]['end_value']);
    $consultation_ended = ($consultation_end - $now) <= 0;

    // Preprocess variable to examine consultation end date relative to
    // the current request timestamp and determine whether it is open
    // or whether it has already closed.
    $variables['content']['consultation_status'] = [
      '#type' => 'html_tag',
      '#tag' => 'span',
      '#attributes' => [
        'class' => [
          'metaListItem',
          'card__meta-type',
        ],
      ],
      '#value' => $consultation_ended ? t('Closed') : t('Open'),
      '#weight' => count($variables['content']) + 1,
    ];
  }

  if ($node->bundle() === 'heritage_site') {
    $historic_map = $node->get('field_historic_map_viewer_link')->getValue();
    $nismr = $node->get('field_nismr_link')->getValue();

    if (!empty($historic_map[0]['uri'])) {
      $variables['content']['field_historic_map_viewer_link'][0]['#title'] = t('View on the Historic Environment Map Viewer');
    }
    if (!empty($nismr[0]['uri'])) {
      $variables['content']['field_nismr_link'][0]['#title'] = t('View details on the NI Sites & Monuments Record (NISMR)');
    }
  }
}

/**
 * Adds the required preprocess variables to the page
 * if there is a parent topic with a landing page that has
 * a banner image associated with it. If these values are
 * detected at the template, it should render the image
 * media with the overlay file on top to create a blended
 * banner image that can appear above the title.
 */
function dept_node_topic_banner(array &$variables) {
  /** @var \Drupal\node\NodeInterface $node */
  $node = &$variables['node'];
  $view_mode = $variables['view_mode'];

  // Only show the banner on full view mode.
  if ($view_mode != 'full') {
    return;
  }

  // Assume topic nodes present this banner as part of $content.
  if ($node->bundle() === 'topic') {
    return;
  }

  // Look up referenced topics.
  $site_topics = NULL;
  foreach (['field_site_topics', 'field_parent_topic'] as $topic_field_name) {
    if ($node->hasField($topic_field_name)) {
      $site_topics = $node->get($topic_field_name)->referencedEntities();
    }
  }

  if (empty($site_topics)) {
    return;
  }

  /** @var \Drupal\node\NodeInterface $topic_node */
  $topic_node = $site_topics[0];

  // Is there a landing page with the same topic reference with a banner?
  $lp_query_ids = \Drupal::entityQuery('node')
    ->condition('type', 'landing_page')
    ->condition('status', 1)
    ->condition('field_site_topics', $topic_node->id())
    ->range(0, 1)
    ->execute();

  $landing_page_node = \Drupal::entityTypeManager()
    ->getStorage('node')
    ->loadMultiple($lp_query_ids);
  $landing_page_node = reset($landing_page_node);

  if (empty($landing_page_node)) {
    return;
  }

  $banner_media = reset($landing_page_node
    ->get('field_banner_image')
    ->referencedEntities()
  );

  if (empty($banner_media)) {
    return;
  }

  $banner_render = \Drupal::entityTypeManager()
    ->getViewBuilder('media')
    ->view($banner_media, 'banner_thin');

  // Put the media render array into the preprocess vars to blend
  // with the overlay image at the template layer.
  $variables['banner_image'] = $banner_render;
  $variables['banner_image']['#weight'] = -100;
}

/**
 * Updates the domain_access value to include the nigov domain if certain
 * conditions are met.
 */
function dept_node_assign_domain_defaults(array $form, FormStateInterface $form_state) {

  $domain_access = $form_state->getValue('field_domain_access');

  // @phpstan-ignore-next-line
  if ($form_state->getFormObject()->getEntity()->bundle() === 'news') {
    // If News is not a press release, remove any existing 'nigov' entry.
    if ($form_state->getValue('field_news_type')[0]['value'] !== 'pressrelease') {
      $form_state->setValue('field_domain_access', array_filter($domain_access, function ($domain) {
        return $domain['target_id'] !== 'nigov';
      }));
      return;
    }
  }

  $domain_access[] = ['target_id' => 'nigov'];

  // Remove any duplicate domain entries.
  array_unique($domain_access, SORT_REGULAR);

  $form_state->setValue('field_domain_access', $domain_access);
}

/**
 * Implements hook_preprocess_page().
 */
function dept_node_preprocess_page(&$variables) {
  if (\Drupal::service('router.admin_context')->isAdminRoute()) {
    return;
  }

  // Apply link manager library to all non-admin pages.
  $variables['#attached']['library'][] = 'dept_node/link_manager';
}
