<?php

/**
 * @file
 * Primary module hooks for dept_dev module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\Core\Site\Settings;
use Drupal\Core\Url;

/**
 * Implements hook_toolbar().
 */
function dept_dev_toolbar() {
  $items = [];

  $config_hostnames = \Drupal::config('dept_dev.settings.toolbar_sites')->get('config_hostnames') ?? 1;
  $url_protocol = \Drupal::config('dept_dev.settings.toolbar_sites')->get('url_protocol') ?? 0;
  $department_manager = \Drupal::service('department.manager');

  $departments = $department_manager->getAllDepartments();

  $links = [];

  foreach ($departments as $department) {

    $links[] = [
      'title' => $department->name(),
      'url' => Url::fromUri($department->url(!$config_hostnames, $url_protocol)),
    ];
  }

  $menu_links = [
    '#theme' => 'links__toolbar_sites',
    '#links' => $links,
    '#attributes' => [
      'class' => ['toolbar-menu'],
    ],
  ];

  $items['sites'] = [
    '#type' => 'toolbar_item',
    'tab' => [
      '#type' => 'link',
      '#title' => t('Sites'),
      '#url' => Url::fromRoute('domain.admin'),
      '#attributes' => [
        'title' => t('Departmental sites'),
        'class' => ['toolbar-icon', 'toolbar-icon-menu'],
      ],
    ],
    'tray' => [
      '#heading' => t('Departmental sites'),
      'children' => $menu_links,
      'configuration' => [
        '#type' => 'link',
        '#title' => 'Configure',
        '#url' => Url::fromRoute('dept_dev.settings.toolbar.sites'),
        // Just borrowing 'Shortcuts' class to move this link to the right.
        '#attributes' => ['class' => ['edit-shortcuts']],
      ],
    ],
    '#cache' => [
      'tags' => ['dept_dev_tools_sites'],
    ],
    '#weight' => 100,
  ];

  return $items;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function dept_dev_preprocess_page(&$variables) {
  // Display warning when Redis isn't configured to run on lando.
  if (!is_null(Settings::get('redis_enabled')) && !Settings::get('redis_enabled')) {
    \Drupal::messenger()->addError("Local Redis is not enable. Change the 'redis_enabled' variable to true under settings.local.php");
  }
}
