<?php

/**
 * @file
 * Primary module hooks for dept_dev module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\Core\Url;
use Drupal\dept_dev\DeptDevLazyBuilders;

/**
 * Implements hook_toolbar().
 */
function dept_dev_toolbar() {
  $items = [];

  $domains = \Drupal::service('entity_type.manager')->getStorage('domain')->loadMultiple();
  $lando_hostnames = \Drupal::config('dept_dev.settings')->get('toolbar_sites_lando_hostname');
  $lando_protocol = \Drupal::config('dept_dev.settings')->get('toolbar_sites_lando_protocol');
  $links = [];

  foreach ($domains as $domain) {
    $url = $domain->getPath();
    if ($lando_hostnames) {
      $protocol = ($lando_protocol) ? 'http' : 'https';

      // Exception for Dept Admin domain, otherwise just replace gov.uk host.
      if ($url === 'https://www.main-bvxea6i-dnvkwx4xjhiza.uk-1.platformsh.site/') {
        $url = "$protocol://dept.lndo.site/";
      }
      else {
        $url = preg_replace('/https?:\/\/(www.)?(.*)(gov.uk)/', "$protocol://$2lndo.site", $url);
      }
    }
    $links[$domain->id()] = [
      'title' => $domain->label(),
      'url' => Url::fromUri($url),
    ];
  }

  $menu_links =[
    '#theme' => 'links__toolbar_sites',
    '#links' => $links,
    '#attributes' => [
      'class' => ['toolbar-menu'],
    ],
  ];

  $items['sites'] = [
    '#type' => 'toolbar_item',
    'tab' => [
      '#type' => 'link',
      '#title' => t('Sites'),
      '#url' => Url::fromRoute('domain.admin'),
      '#attributes' => [
        'title' => t('Departmental sites'),
        'class' => ['toolbar-icon', 'toolbar-icon-menu'],
      ],
    ],
    'tray' => [
      '#heading' => t('Departmental sites'),
      'children' => $menu_links,
      'configuration' => [
        '#type' => 'link',
        '#title' => 'Configure',
        '#url' => Url::fromRoute('dept_dev.settings'),
        // Just borrowing 'Shortcuts' class to move this link to the right.
        '#attributes' => ['class' => ['edit-shortcuts']],
      ],
    ],
    '#weight' => 100,
  ];

  return $items;
}
