# The name given to the MariaDB service (lowercase alphanumeric only).
db:
  # The type of your service (mariadb), which uses the format
  # 'type:version'. Be sure to consult the MariaDB documentation
  # (https://docs.platform.sh/configuration/services/mysql.html#supported-versions)
  # when choosing a version. If you specify a version number which is not available,
  # the CLI will return an error.
  type: mariadb:11.8
  # The disk attribute is the size of the persistent disk (in MB) allocated to the service.
  disk: 7168
  configuration:
    schemas:
      - main
    endpoints:
      dept:
        default_schema: main
        privileges:
          main: admin

# Fudging the service name forces a full rebuild with any new config.
solr_9_6:
  type: solr:9.6
  disk: 1024
  configuration:
    cores:
      default:
        conf_dir: !archive "solr_9.x_config/"
    endpoints:
      solr:
        core: default

redis:
  type: "redis:8.0"
  configuration:
    maxmemory_policy: allkeys-lfu
