# DDEV project level config. See https://ddev.readthedocs.io/en/stable/users/configuration/config/
# for full set of options that can be used.
name: dept
type: drupal
docroot: web
php_version: "8.2"
xdebug_enabled: false
additional_hostnames:
    - nigov
    - communities-ni
    - daera-ni
    - economy-ni
    - education-ni
    - executiveoffice-ni
    - finance-ni
    - health-ni
    - infrastructure-ni
    - justice-ni
additional_fqdns: []
database:
    type: mariadb
    version: "10.11"
timezone: Europe/Dublin
composer_version: "2"
nodejs_version: 14
hooks:
  post-start:
    - exec: "composer install --optimize-autoloader --no-interaction"
    - exec: ".ddev/homeadditions/appserver_build.sh"
