# DDEV project level config. See https://ddev.readthedocs.io/en/stable/users/configuration/config/
# for full set of options that can be used.
name: dept
type: drupal
docroot: web
php_version: "8.2"
xdebug_enabled: false
additional_hostnames:
    - nigov
    - communities-ni
    - daera-ni
    - economy-ni
    - education-ni
    - executiveoffice-ni
    - finance-ni
    - health-ni
    - infrastructure-ni
    - justice-ni
additional_fqdns: []
database:
    type: mariadb
    version: "10.11"
timezone: Europe/Dublin
composer_version: "2"
nodejs_version: 14
fail_on_hook_fail: true
hooks:
  pre-start:
    # Ensure env var file is deployed; needs to be filled in manually for sensitive values.
    - exec-host: "if [ ! -d /app/.ddev/.env ]; then cp -v /app/.env.sample /app/.ddev/.env; fi"
    - exec-host: "echo PLEASE FILL IN SENSITIVE ENV VAR VALUES IN .ddev/.env THEN RUN ddev restart"
    - exec-host: "exit 1"
  post-start:
    - composer: install
    - exec: ".ddev/homeadditions/appserver_build.sh"
  post-import-db:
    # Ensure the local config split profile is detected and active.
    - exec: "drush cr"
    # Import any local config split profile overrides.
    - exec: "drush cim -y"
