<?php

/**
 * @file
 * Hooks and functions for Revision Delete Tools.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function revision_delete_tools_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {

    case 'help.page.revision_delete_tools':

      $output = '';
      $output .= '<h3>' . t('Introduction') . '</h3>';
      $output .= '<p>' . t('The Revision Delete Tools module provides Drush commands to manage revisions and multi-select actions on the node revisions page.') . '</p>';
      $output .= '<h3>' . t('Configuration') . '</h3>';
      $output .= '<p>' . t('Configure the module at the <a href=":config-url">configuration page</a>. ', [':config-url' => Url::fromRoute('revision_delete_tools.configuration')->toString()]) . '</p>';
      $output .= '<h3>' . t('Permissions') . '</h3>';
      $output .= '<p>' . t('The module provides <a href=":permissions-url"> permissions</a> for the multi-select actions on the node revisions page.', [':permissions-url' => Url::fromRoute('user.admin_permissions.module', ['modules' => 'revision_delete_tools'])->toString()]) . '</p>';
      $output .= '<dl>';
      $output .= '<dt><strong>' . t('Allow bulk selection of revisions') . '</strong></dt>';
      $output .= '<dd>' . t('Displays checkboxes for each revision and a drop down menu of actions.') . '</dd>';
      $output .= '<dt><strong>' . t('Allow bulk deletion of newer revisions') . '</strong></dt>';
      $output .= '<dd>' . t('Allows to user to select the bulk action to delete all revisions newer than the current revision.') . '</dd>';
      $output .= '<dt><strong>' . t('Allow bulk deletion of older revisions') . '</strong></dt>';
      $output .= '<dd>' . t('Allows to user to select the bulk action to delete all revisions older than the current revision.') . '</dd>';
      $output .= '</dl>';

      return $output;
  }
}

/**
 * Implements hook_form_alter().
 */
function revision_delete_tools_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Display if enabled in RDT config form and if the form ID matches:
  // - (Core) node_revision_overview_form.
  // - (Diff module) revision_overview_form.
  if (Drupal::configFactory()->get('revision_delete_tools.configuration')->get('bulk_delete') &&
    in_array($form_id, [
      'revision_overview_form',
      'node_revision_overview_form',
      'revision_overview_form',
    ])) {

    $user = \Drupal::currentUser();

    if (!$user->hasPermission('bulk select revisions')) {
      return;
    }

    array_unshift($form['node_revisions_table']['#header'], [
      'data' => [
        '#type' => 'checkbox',
        '#attributes' => [
          'title' => t('Click to select/deselect all.'),
          'class' => ['select-all']
        ],
      ],
    ]);

    foreach ($form['node_revisions_table'] as $key => &$row) {
      if (is_numeric($key)) {
        // If a revision cannot be reverted it must be the current revision.
        $is_current = isset($row['operations']['#links']['revert']) ? FALSE : TRUE;
        $vid = 0;

        if (!$is_current) {
          // Extract the revision ID from the revert operation link.
          $revert_url = $row['operations']['#links']['revert']['url'];
          if (isset($revert_url)) {
            $vid = $revert_url->getRouteParameters()['node_revision'];
          }
        }

        $row = array_merge([
          'selected_vid' => [
            '#type' => 'checkbox',
            '#disabled' => $is_current,
            '#default_value' => FALSE,
            '#return_value' => $vid,
            '#attributes' => ['class' => ['row-checkbox']],
          ]
        ],
          $row
        );
      }
    }

    $form['bulk_actions'] = [
      '#type' => 'container',
      '#weight' => -10,
      '#attributes' => ['class' => ['container-inline']],
    ];

    $form['bulk_actions']['action'] = [
      '#type' => 'select',
      '#title' => t('Delete'),
      '#options' => [
        'delete' => t('the selected revisions'),
      ],
      '#empty_option' => t('- Select -'),
      '#attributes' => ['aria-label' => ['Bulk delete']],
    ];

    if ($user->hasPermission('bulk delete newer revisions')) {
      $form['bulk_actions']['action']['#options']['newer'] = t('all revisions newer than current revision');
    }

    if ($user->hasPermission('bulk delete older revisions')) {
      $form['bulk_actions']['action']['#options']['older'] = t('all revisions older than current revision');
    }

    $form['bulk_actions']['apply'] = [
      '#type' => 'submit',
      '#value' => t('Apply'),
      '#submit' => ['revision_delete_tools_bulk_revisions_submit'],
      '#validate' => ['revision_delete_tools_revisions_validate'],
    ];

    $form['#attached']['library'][] = 'revision_delete_tools/bulk_actions';
  }
}

/**
 * Validation handler for bulk actions.
 */
function revision_delete_tools_revisions_validate($form, FormStateInterface $form_state) {
  $action = $form_state->getValue('action');

  if (empty($action)) {
    $form_state->setErrorByName('action', t('Please select an action.'));
    return;
  }

  if ($action == 'delete') {
    $selected_vids = [];
    $table = $form_state->getValue('node_revisions_table');

    foreach ($table as $row) {
      if ($row['selected_vid']) {
        $selected_vids[] = $row['selected_vid'];
      }
    }

    if (empty($selected_vids)) {
      $form_state->setErrorByName('action', t('Please select off at least one revision using the checkboxes.'));
    }
  }
}

/**
 * Submit handler for bulk actions.
 */
function revision_delete_tools_bulk_revisions_submit($form, FormStateInterface $form_state) {
  $action = $form_state->getValue('action');

  if ($action == 'delete') {
    $selected_vids = [];
    $table = $form_state->getValue('node_revisions_table');

    foreach ($table as $row) {
      if ($row['selected_vid']) {
        $selected_vids[] = $row['selected_vid'];
      }
    }

    if (!empty($selected_vids)) {
      $node_storage = \Drupal::entityTypeManager()->getStorage('node');
      foreach ($selected_vids as $vid) {
        $node_storage->deleteRevision($vid);
      }
      \Drupal::messenger()->addMessage(t('Deleted @count revision(s).', [
        '@count' => count($selected_vids),
      ]));
    }
  }

  if ($action == 'older' || $action == 'newer') {
    $node = \Drupal::routeMatch()->getParameter('node');
    $form_state->setRedirect('revision_delete_tools.bulk_delete_confirmation', [
      'node' => $node->id(),
      'action' => $action
    ]);
  }
}
